analog:
  plants:            # 机组模拟量故障点统计原始点
    - id: 2001                         # 机组id
      points:
        - ZL.01.AI0001
        - ZL.01.AI0002
        - ZL.01.AI0004
        - ZL.01.AI0005
        - ZL.01.AI0006
        - ZL.01.AI0007
        - ZL.01.AI0010
        - ZL.01.AI0011
        - ZL.01.AI0012
        - ZL.01.AI0013
        - ZL.01.AI0014
        - ZL.01.AI0016
        - ZL.01.AI0017
        - ZL.01.AI0018
        - ZL.01.AI0019
        - ZL.01.AI0020
        - ZL.01.AI0021
        - ZL.01.AI0022
        - ZL.01.AI0023
        - ZL.01.AI0025
        - ZL.01.AI0201
        - ZL.01.AI0202
        - ZL.01.AI0203
        - ZL.01.AI0204
        - ZL.01.AI0205
        - ZL.01.AI0206
        - ZL.01.AI0207
        - ZL.01.AI0208
        - ZL.01.AI0215
        - ZL.01.AI0216
        - ZL.01.AI0217
        - ZL.01.AI0218
        - ZL.01.AI0219
        - ZL.01.AI0220
        - ZL.01.AI0221
        - ZL.01.AI0222
        - ZL.01.AI0223
        - ZL.01.AI0224
        - ZL.01.AI0225
        - ZL.01.AI0226
        - ZL.01.AI0235
        - ZL.01.AI0236
        - ZL.01.AI0237
        - ZL.01.AI0238
        - ZL.01.AI0239
        - ZL.01.AI0240
        - ZL.01.AI0241
        - ZL.01.AI0242
        - ZL.01.AI0243
        - ZL.01.AI0244
        - ZL.01.AI0245
        - ZL.01.AI0246
        - ZL.01.AI0247
        - ZL.01.AI0248
        - ZL.01.AI0249
        - ZL.01.AI0250
        - ZL.01.AI0251
        - ZL.01.AI0252
        - ZL.01.AI0253
        - ZL.01.AI0254
        - ZL.01.AI0255
        - ZL.01.AI0256
        - ZL.01.AI0257
        - ZL.01.AI0258
        - ZL.01.AI0259
        - ZL.01.AI0260
        - ZL.01.AI0261
        - ZL.01.AI0262
        - ZL.01.AI0263
        - ZL.01.AI0264
        - ZL.01.AI0297
        - ZL.01.AI0298
        - ZL.01.AI0299
        - ZL.01.AI0300
        - ZL.01.AI0301
    - id: 2
      points:
        - ZL.02.AI0001
        - ZL.02.AI0004
        - ZL.02.AI0005
        - ZL.02.AI0006
        - ZL.02.AI0007
        - ZL.02.AI0008
        - ZL.02.AI0009
        - ZL.02.AI0010
        - ZL.02.AI0011
        - ZL.02.AI0012
        - ZL.02.AI0013
        - ZL.02.AI0014
        - ZL.02.AI0015
        - ZL.02.AI0016
        - ZL.02.AI0017
        - ZL.02.AI0021
        - ZL.02.AI0023
        - ZL.02.AI0025
        - ZL.02.AI0026
        - ZL.02.AI0199
        - ZL.02.AI0201
        - ZL.02.AI0202
        - ZL.02.AI0203
        - ZL.02.AI0204
        - ZL.02.AI0205
        - ZL.02.AI0206
        - ZL.02.AI0207
        - ZL.02.AI0208
        - ZL.02.AI0209
        - ZL.02.AI0210
        - ZL.02.AI0211
        - ZL.02.AI0212
        - ZL.02.AI0213
        - ZL.02.AI0214
        - ZL.02.AI0215
        - ZL.02.AI0216
        - ZL.02.AI0217
        - ZL.02.AI0218
        - ZL.02.AI0219
        - ZL.02.AI0220
        - ZL.02.AI0221
        - ZL.02.AI0222
        - ZL.02.AI0223
        - ZL.02.AI0224
        - ZL.02.AI0225
        - ZL.02.AI0226
        - ZL.02.AI0227
        - ZL.02.AI0228
        - ZL.02.AI0229
        - ZL.02.AI0230
        - ZL.02.AI0231
        - ZL.02.AI0232
        - ZL.02.AI0233
        - ZL.02.AI0234
        - ZL.02.AI0235
        - ZL.02.AI0236
        - ZL.02.AI0237
        - ZL.02.AI0238
        - ZL.02.AI0239
        - ZL.02.AI0240
        - ZL.02.AI0241
        - ZL.02.AI0242
        - ZL.02.AI0243
        - ZL.02.AI0244
        - ZL.02.AI0245
        - ZL.02.AI0246
        - ZL.02.AI0247
        - ZL.02.AI0248
        - ZL.02.AI0249
        - ZL.02.AI0250
        - ZL.02.AI0251
        - ZL.02.AI0252
        - ZL.02.AI0253
        - ZL.02.AI0254
        - ZL.02.AI0259
        - ZL.02.AI0260
        - ZL.02.AI0261
        - ZL.02.AI0262
        - ZL.02.AI0267
        - ZL.02.AI0268
        - ZL.02.AI0269
        - ZL.02.AI0270
        - ZL.02.AI0275
    - id: 3
      points:
        - ZL.03.AI0001
        - ZL.03.AI0004
        - ZL.03.AI0005
        - ZL.03.AI0006
        - ZL.03.AI0007
        - ZL.03.AI0008
        - ZL.03.AI0009
        - ZL.03.AI0010
        - ZL.03.AI0011
        - ZL.03.AI0012
        - ZL.03.AI0013
        - ZL.03.AI0014
        - ZL.03.AI0015
        - ZL.03.AI0016
        - ZL.03.AI0017
        - ZL.03.AI0021
        - ZL.03.AI0023
        - ZL.03.AI0024
        - ZL.03.AI0025
        - ZL.03.AI0199
        - ZL.03.AI0201
        - ZL.03.AI0202
        - ZL.03.AI0203
        - ZL.03.AI0204
        - ZL.03.AI0205
        - ZL.03.AI0206
        - ZL.03.AI0207
        - ZL.03.AI0208
        - ZL.03.AI0209
        - ZL.03.AI0210
        - ZL.03.AI0211
        - ZL.03.AI0212
        - ZL.03.AI0213
        - ZL.03.AI0214
        - ZL.03.AI0215
        - ZL.03.AI0216
        - ZL.03.AI0217
        - ZL.03.AI0218
        - ZL.03.AI0219
        - ZL.03.AI0220
        - ZL.03.AI0221
        - ZL.03.AI0222
        - ZL.03.AI0223
        - ZL.03.AI0224
        - ZL.03.AI0225
        - ZL.03.AI0226
        - ZL.03.AI0227
        - ZL.03.AI0228
        - ZL.03.AI0229
        - ZL.03.AI0230
        - ZL.03.AI0231
        - ZL.03.AI0232
        - ZL.03.AI0233
        - ZL.03.AI0234
        - ZL.03.AI0235
        - ZL.03.AI0236
        - ZL.03.AI0237
        - ZL.03.AI0238
        - ZL.03.AI0239
        - ZL.03.AI0240
        - ZL.03.AI0241
        - ZL.03.AI0242
        - ZL.03.AI0243
        - ZL.03.AI0244
        - ZL.03.AI0245
        - ZL.03.AI0246
        - ZL.03.AI0247
        - ZL.03.AI0248
        - ZL.03.AI0249
        - ZL.03.AI0250
        - ZL.03.AI0252
        - ZL.03.AI0253
        - ZL.03.AI0254
        - ZL.03.AI0259
        - ZL.03.AI0261
        - ZL.03.AI0267
        - ZL.03.AI0268
        - ZL.03.AI0270
        - ZL.03.AI0275
        - ZL.03.AI0277
        - ZL.03.AI0278
        - ZL.03.AI0279
        - ZL.03.AI0280
    - id: 4
      points:
        - ZL.04.AI0001
        - ZL.04.AI0009
        - ZL.04.AI0010
        - ZL.04.AI0011
        - ZL.04.AI0012
        - ZL.04.AI0013
        - ZL.04.AI0014
        - ZL.04.AI0015
        - ZL.04.AI0016
        - ZL.04.AI0017
        - ZL.04.AI0022
        - ZL.04.AI0023
        - ZL.04.AI0193
        - ZL.04.AI0194
        - ZL.04.AI0195
        - ZL.04.AI0199
        - ZL.04.AI0201
        - ZL.04.AI0202
        - ZL.04.AI0203
        - ZL.04.AI0204
        - ZL.04.AI0205
        - ZL.04.AI0206
        - ZL.04.AI0207
        - ZL.04.AI0208
        - ZL.04.AI0209
        - ZL.04.AI0210
        - ZL.04.AI0211
        - ZL.04.AI0212
        - ZL.04.AI0213
        - ZL.04.AI0214
        - ZL.04.AI0215
        - ZL.04.AI0216
        - ZL.04.AI0217
        - ZL.04.AI0218
        - ZL.04.AI0219
        - ZL.04.AI0220
        - ZL.04.AI0221
        - ZL.04.AI0222
        - ZL.04.AI0223
        - ZL.04.AI0224
        - ZL.04.AI0225
        - ZL.04.AI0226
        - ZL.04.AI0227
        - ZL.04.AI0228
        - ZL.04.AI0229
        - ZL.04.AI0230
        - ZL.04.AI0231
        - ZL.04.AI0232
        - ZL.04.AI0233
        - ZL.04.AI0234
        - ZL.04.AI0235
        - ZL.04.AI0236
        - ZL.04.AI0237
        - ZL.04.AI0238
        - ZL.04.AI0239
        - ZL.04.AI0240
        - ZL.04.AI0241
        - ZL.04.AI0242
        - ZL.04.AI0243
        - ZL.04.AI0244
        - ZL.04.AI0245
        - ZL.04.AI0246
        - ZL.04.AI0247
        - ZL.04.AI0248
        - ZL.04.AI0249
        - ZL.04.AI0250
        - ZL.04.AI0251
        - ZL.04.AI0252
        - ZL.04.AI0253
        - ZL.04.AI0254
        - ZL.04.AI0255
        - ZL.04.AI0256
        - ZL.04.AI0257
        - ZL.04.AI0258
        - ZL.04.AI0259
        - ZL.04.AI0260
        - ZL.04.AI0261
        - ZL.04.AI0262
        - ZL.04.AI0263
        - ZL.04.AI0264
        - ZL.04.AI0265
        - ZL.04.AI0266
        - ZL.04.AI0267
        - ZL.04.AI0268
        - ZL.04.AI0269
        - ZL.04.AI0270
        - ZL.04.AI0271
        - ZL.04.AI0272
        - ZL.04.AI0273
        - ZL.04.AI0274
        - ZL.04.AI0275
    - id: 5
      points:
        - ZL.05.AI0007
        - ZL.05.AI0008
        - ZL.05.AI0014
        - ZL.05.AI0029
        - ZL.05.AI0030
        - ZL.05.AI0031
        - ZL.05.AI0035
        - ZL.05.AI0036
        - ZL.05.AI0037
        - ZL.05.AI0038
        - ZL.05.AI0039
        - ZL.05.AI0041
        - ZL.05.AI0042
        - ZL.05.AI0046
        - ZL.05.AI0050
        - ZL.05.AI0054
        - ZL.05.AI0055
        - ZL.05.AI0056
        - ZL.05.AI0057
        - ZL.05.AI0058
        - ZL.05.AI0059
        - ZL.05.AI0060
        - ZL.05.AI0062
        - ZL.05.AI0063
        - ZL.05.AI0064
        - ZL.05.AI0132
        - ZL.05.AI0133
        - ZL.05.AI0134
        - ZL.05.AI0299
        - ZL.05.AI0300
        - ZL.05.AI0301
        - ZL.05.AI0302
        - ZL.05.AI0303
        - ZL.05.AI0304
        - ZL.05.AI0305
        - ZL.05.AI0306
        - ZL.05.AI0307
        - ZL.05.AI0308
        - ZL.05.AI0309
        - ZL.05.AI0310
        - ZL.05.AI0311
        - ZL.05.AI0312
        - ZL.05.AI0313
        - ZL.05.AI0314
        - ZL.05.AI0315
        - ZL.05.AI0316
        - ZL.05.AI0317
        - ZL.05.AI0318
        - ZL.05.AI0319
        - ZL.05.AI0320
        - ZL.05.AI0321
        - ZL.05.AI0322
        - ZL.05.AI0323
        - ZL.05.AI0324
        - ZL.05.AI0325
        - ZL.05.AI0326
        - ZL.05.AI0327
        - ZL.05.AI0328
        - ZL.05.AI0329
        - ZL.05.AI0330
        - ZL.05.AI0331
        - ZL.05.AI0332
        - ZL.05.AI0333
        - ZL.05.AI0334
        - ZL.05.AI0335
        - ZL.05.AI0336
        - ZL.05.AI0337
        - ZL.05.AI0338
        - ZL.05.AI0339
        - ZL.05.AI0340
        - ZL.05.AI0341
        - ZL.05.AI0342
        - ZL.05.AI0343
        - ZL.05.AI0344
        - ZL.05.AI0345
        - ZL.05.AI0346
        - ZL.05.AI0347
        - ZL.05.AI0348
        - ZL.05.AI0349
        - ZL.05.AI0350
        - ZL.05.AI0351
        - ZL.05.AI0352
        - ZL.05.AI0353
        - ZL.05.AI0354
        - ZL.05.AI0355
        - ZL.05.AI0356
        - ZL.05.AI0357
        - ZL.05.AI0358
        - ZL.05.AI0359
        - ZL.05.AI0360
        - ZL.05.AI0361
        - ZL.05.AI0362
        - ZL.05.AI0363
        - ZL.05.AI0364
        - ZL.05.AI0365
        - ZL.05.AI0366
        - ZL.05.AI0367
        - ZL.05.AI0368
        - ZL.05.AI0369
        - ZL.05.AI0370
        - ZL.05.AI0371
        - ZL.05.AI0372
        - ZL.05.AI0373
        - ZL.05.AI0374
        - ZL.05.AI0375
        - ZL.05.AI0376
        - ZL.05.AI0377
        - ZL.05.AI0378
        - ZL.05.AI0379
        - ZL.05.AI0380
        - ZL.05.AI0381
        - ZL.05.AI0382
        - ZL.05.AI0383
        - ZL.05.AI0384
        - ZL.05.AI0385
        - ZL.05.AI0386
        - ZL.05.AI0387
        - ZL.05.AI0388
        - ZL.05.AI0389
        - ZL.05.AI0390
        - ZL.05.AI0391
        - ZL.05.AI0392
        - ZL.05.AI0418
        - ZL.05.AI0419
        - ZL.05.AI0420
        - ZL.05.AI0421
        - ZL.05.AI0422
        - ZL.05.AI0423
        - ZL.05.AI0424
        - ZL.05.AI0425
        - ZL.05.AI0426
        - ZL.05.AI0427
        - ZL.05.AI0428
        - ZL.05.AI0429
        - ZL.05.AI0430
        - ZL.05.AI0431
        - ZL.05.AI0432
        - ZL.05.AI0433
        - ZL.05.AI0434
        - ZL.05.AI0435
        - ZL.05.AI0436
        - ZL.05.AI0437
        - ZL.05.AI0438
        - ZL.05.AI0439
        - ZL.05.AI0440
        - ZL.05.AI0441
        - ZL.05.AI0442
    - id: 6
      points:
        - ZL.06.AI0007
        - ZL.06.AI0008
        - ZL.06.AI0014
        - ZL.06.AI0029
        - ZL.06.AI0030
        - ZL.06.AI0031
        - ZL.06.AI0035
        - ZL.06.AI0036
        - ZL.06.AI0037
        - ZL.06.AI0038
        - ZL.06.AI0039
        - ZL.06.AI0046
        - ZL.06.AI0050
        - ZL.06.AI0054
        - ZL.06.AI0055
        - ZL.06.AI0056
        - ZL.06.AI0057
        - ZL.06.AI0058
        - ZL.06.AI0059
        - ZL.06.AI0060
        - ZL.06.AI0062
        - ZL.06.AI0063
        - ZL.06.AI0064
        - ZL.06.AI0299
        - ZL.06.AI0300
        - ZL.06.AI0301
        - ZL.06.AI0302
        - ZL.06.AI0303
        - ZL.06.AI0304
        - ZL.06.AI0305
        - ZL.06.AI0306
        - ZL.06.AI0307
        - ZL.06.AI0308
        - ZL.06.AI0309
        - ZL.06.AI0310
        - ZL.06.AI0311
        - ZL.06.AI0312
        - ZL.06.AI0313
        - ZL.06.AI0314
        - ZL.06.AI0315
        - ZL.06.AI0316
        - ZL.06.AI0317
        - ZL.06.AI0318
        - ZL.06.AI0319
        - ZL.06.AI0320
        - ZL.06.AI0321
        - ZL.06.AI0322
        - ZL.06.AI0323
        - ZL.06.AI0324
        - ZL.06.AI0325
        - ZL.06.AI0326
        - ZL.06.AI0327
        - ZL.06.AI0328
        - ZL.06.AI0329
        - ZL.06.AI0330
        - ZL.06.AI0331
        - ZL.06.AI0332
        - ZL.06.AI0333
        - ZL.06.AI0334
        - ZL.06.AI0335
        - ZL.06.AI0336
        - ZL.06.AI0337
        - ZL.06.AI0338
        - ZL.06.AI0339
        - ZL.06.AI0340
        - ZL.06.AI0341
        - ZL.06.AI0342
        - ZL.06.AI0343
        - ZL.06.AI0344
        - ZL.06.AI0345
        - ZL.06.AI0346
        - ZL.06.AI0347
        - ZL.06.AI0348
        - ZL.06.AI0349
        - ZL.06.AI0350
        - ZL.06.AI0351
        - ZL.06.AI0352
        - ZL.06.AI0353
        - ZL.06.AI0354
        - ZL.06.AI0355
        - ZL.06.AI0356
        - ZL.06.AI0357
        - ZL.06.AI0358
        - ZL.06.AI0359
        - ZL.06.AI0360
        - ZL.06.AI0361
        - ZL.06.AI0362
        - ZL.06.AI0363
        - ZL.06.AI0364
        - ZL.06.AI0365
        - ZL.06.AI0366
        - ZL.06.AI0367
        - ZL.06.AI0368
        - ZL.06.AI0369
        - ZL.06.AI0370
        - ZL.06.AI0371
        - ZL.06.AI0372
        - ZL.06.AI0373
        - ZL.06.AI0374
        - ZL.06.AI0375
        - ZL.06.AI0376
        - ZL.06.AI0377
        - ZL.06.AI0378
        - ZL.06.AI0379
        - ZL.06.AI0380
        - ZL.06.AI0381
        - ZL.06.AI0382
        - ZL.06.AI0383
        - ZL.06.AI0384
        - ZL.06.AI0385
        - ZL.06.AI0386
        - ZL.06.AI0387
        - ZL.06.AI0388
        - ZL.06.AI0389
        - ZL.06.AI0390
        - ZL.06.AI0391
        - ZL.06.AI0392
        - ZL.06.AI0418
        - ZL.06.AI0419
        - ZL.06.AI0420
        - ZL.06.AI0421
        - ZL.06.AI0422
        - ZL.06.AI0423
        - ZL.06.AI0424
        - ZL.06.AI0425
        - ZL.06.AI0426
        - ZL.06.AI0427
        - ZL.06.AI0428
        - ZL.06.AI0429
        - ZL.06.AI0430
        - ZL.06.AI0431
        - ZL.06.AI0432
        - ZL.06.AI0433
        - ZL.06.AI0434
        - ZL.06.AI0435
        - ZL.06.AI0436
        - ZL.06.AI0437
        - ZL.06.AI0438
        - ZL.06.AI0439
        - ZL.06.AI0440
        - ZL.06.AI0441
        - ZL.06.AI0442